title: Scratchpad 
description: Posts around programming languages
baseurl: ""
url: "https://paulls20.github.io/"
future: true
highlighter: rouge

exclude:
  - README.adoc
  - Gemfile

asciidoctor:
  attributes:
    - idprefix=_
    - source-highlighter=rouge

plugins:
  - jekyll-asciidoc
  - jekyll-time-to-read
  - jekyll-redirect-from
